project:
  type: website
  output-dir: docs

website:
  title: "Diogo Carapito"
  favicon: favicon.ico
  navbar:
    left:
      - about.qmd
    right:
      - icon: twitter
        href: https://twitter.com/diogocarapito
      - icon: github
        href: https://github.com/diogocarapito
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css



