name: Clone Master Branch to gh-pages branch

on:
  pull_request:
    branches: [master]

jobs:
  clone:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout master branch
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Create gh-pages
      run: |
        git checkout -b gh-page
        git push -u origin tgh-pages
